// <auto-generated />
using System;
using FrostedCornerWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrostedCornerWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250724011504_RemoveItemIdFromDietaryRestrictions")]
    partial class RemoveItemIdFromDietaryRestrictions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DietaryRestrictionItem", b =>
                {
                    b.Property<int>("DietaryRestrictionsDietaryRestrictionId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("DietaryRestrictionsDietaryRestrictionId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("DietaryRestrictionItem");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.DietaryRestriction", b =>
                {
                    b.Property<int>("DietaryRestrictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DietaryRestrictionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DietaryRestrictionId");

                    b.ToTable("DietaryRestrictions");

                    b.HasData(
                        new
                        {
                            DietaryRestrictionId = 1,
                            Name = "Vegan"
                        },
                        new
                        {
                            DietaryRestrictionId = 2,
                            Name = "Vegetarian"
                        },
                        new
                        {
                            DietaryRestrictionId = 3,
                            Name = "Gluten-Free"
                        },
                        new
                        {
                            DietaryRestrictionId = 4,
                            Name = "Nut-Free"
                        },
                        new
                        {
                            DietaryRestrictionId = 5,
                            Name = "Dairy-Free"
                        });
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.Franchise", b =>
                {
                    b.Property<int>("FranchiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FranchiseId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FranchiseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FranchiseId");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.FranchiseItem", b =>
                {
                    b.Property<int>("FranchiseItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FranchiseItemId"));

                    b.Property<string>("CustomColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CustomPrice")
                        .HasColumnType("real");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("FranchiseItemId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ItemId");

                    b.ToTable("FranchiseItems");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("FranchiseItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.HasKey("OrderItemId");

                    b.HasIndex("FranchiseItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.SuppliesItem", b =>
                {
                    b.Property<int>("SuppliesItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuppliesItemId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.Property<int?>("SuppliesOrderId")
                        .HasColumnType("int");

                    b.HasKey("SuppliesItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("SuppliesOrderId");

                    b.ToTable("SuppliesItems");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.SuppliesOrder", b =>
                {
                    b.Property<int>("SuppliesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuppliesOrderId"));

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("SuppliesOrderId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("SuppliesOrders");
                });

            modelBuilder.Entity("DietaryRestrictionItem", b =>
                {
                    b.HasOne("FrostedCornerWebAPI.Models.DietaryRestriction", null)
                        .WithMany()
                        .HasForeignKey("DietaryRestrictionsDietaryRestrictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrostedCornerWebAPI.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.FranchiseItem", b =>
                {
                    b.HasOne("FrostedCornerWebAPI.Models.Franchise", "Franchise")
                        .WithMany("FranchiseItems")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrostedCornerWebAPI.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.OrderItem", b =>
                {
                    b.HasOne("FrostedCornerWebAPI.Models.FranchiseItem", "FranchiseItem")
                        .WithMany()
                        .HasForeignKey("FranchiseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrostedCornerWebAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FranchiseItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.SuppliesItem", b =>
                {
                    b.HasOne("FrostedCornerWebAPI.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrostedCornerWebAPI.Models.SuppliesOrder", null)
                        .WithMany("SuppliesItems")
                        .HasForeignKey("SuppliesOrderId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.SuppliesOrder", b =>
                {
                    b.HasOne("FrostedCornerWebAPI.Models.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.Franchise", b =>
                {
                    b.Navigation("FranchiseItems");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FrostedCornerWebAPI.Models.SuppliesOrder", b =>
                {
                    b.Navigation("SuppliesItems");
                });
#pragma warning restore 612, 618
        }
    }
}
